#
# Copyright 2019-2020 DJANTA, LLC (https://www.djanta.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed toMap in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Pull Request

on:
  push:
    branches:
      - feature/*
      - upgrade/*
      - addon/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - name: GitHub credentials configuration
        shell: bash
        run: |
          git config user.name "${{ secrets.GH_USER }}"
          git config user.email "${{ secrets.GH_USER_EMAIL }}"
          git config credential.helper "store --file=.git/credentials"
          echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > .git/credentials

      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
#          echo ::set-output name=image_id_cache::${IMAGE_ID_CACHE}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "[AUTO] - Auto created [P/R] on ${GITHUB_REF}"
          committer: ${{ github.event.pusher.name }} <${{ github.event.pusher.email }}>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[PR: #${{ github.run_number }}] from ${{ github.ref }} by (${{ github.event.head_commit.committer.name }})'
          body: |
            - Auto-generated pull request by [create-pull-request][1]
            - P/R by (${{ github.event.head_commit.committer.name }}) on branch: ${GITHUB_REF} after pushed) with the following message
            - ${{ github.event.head_commit.message }}

            [1]: https://github.com/$GITHUB_REPOSITORY/pull
          labels: report, automated pr
          assignees: stanislaska
          reviewers: stanislaska
          team-reviewers: owners, maintainers
          draft: false
          branch: patch
#          request-to-parent: false
          branch-suffix: short-commit-hash

      - name: Create or Update Project Card
        id: coupc
        uses: peter-evans/create-or-update-project-card@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project-name: Cloud Docker
          column-name: To do
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
      - name: Check card (create or update) output
        run: echo ${{ steps.coupc.outputs.card-id }}
